name: Google K8s Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCR_TT_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_TT_KEY }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t gcr.io/trusttrip-447621/frontend:latest ./myApp
          docker push gcr.io/trusttrip-447621/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCR_TT_KEY }}

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl
      
      - name: Install gke-gcloud-auth-plugin
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
          echo "export PATH=$PATH:/usr/lib/google-cloud-sdk/bin" >> $GITHUB_ENV
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials trusttrip-server-cluster \
            --region europe-west1 \
            --project trusttrip-447621

      - name: Deploy to Kubernetes
        run: kubectl apply -f myApp/k8s/frontend-deployment.yaml

      - name: Restart frontend deployment
        run: kubectl rollout restart deployment/frontend

