name: Deploy Frontend-Dev to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Github Actions Authorization for Google Cloud Setup
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCR_TT_KEY }}

      - name: Log in to Google Container Registry
       user: docker/login-action@v2
       with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GKE_TT_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCR_TT_PROJECT_ID }}/frontend-dev:latest -f myApp/Dockerfile myApp

      - name: Push Docker image
        run: docker push gcr.io/trusttrip-447621/frontend-dev:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend-dev \
            --image gcr.io/trusttrip-447621/frontend-dev:latest \
            --platform managed \
            --region europe-west1  \
            --allow-unauthenticated \
            --port 8080
