name: Deploy Frontend-Dev to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCR_TT_PROJECT_ID }}
        service_account_key: ${{ secrets.GCR_TT_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/trusttrip-447621/frontend-dev:latest -f myApp/Dockerfile myApp

    - name: Push Docker image
      run: docker push gcr.io/trusttrip-447621/frontend-dev:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy frontend-dev \
          --image gcr.io/trusttrip-447621/frontend-dev:latest \
          --platform managed \
          --region europe-west1  \
          --allow-unauthenticated \
          --port 8080